[server]
enableStaticServing=true

[[theme.fontFaces]]
family="Inter"
url="app/static/Inter-VariableFont_opsz,wght.ttf"
style="normal"

[[theme.fontFaces]]
family="Inter"
url="app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style="italic"

[[theme.fontFaces]]
family="RobotoMono"
url="app/static/RobotoMono-VariableFont_wght.ttf"
style="normal"

[[theme.fontFaces]]
family="RobotoMono"
url="app/static/RobotoMono-Italic-VariableFont_wght.ttf"
style="italic"

[theme]
font="Inter"
codeFont="RobotoMono"
# base="dark"
primaryColor="goldenrod"
borderColor="gold"
showWidgetBorder=true

[theme.sidebar]
showWidgetBorder=true